### ISSUE TITLE
add Python3.8 support

### ISSUE THREAD

**Issue by Lulu-Bertin** [DLZaan/apapi#15]
We want to use Anaplan API on constrained environments like Composer that only provision Airflow images shipped with Python 3.8

PR Lulu-Bertin:feat/add_support_for_py38 [fbc8383](https://github.com/DLZaan/apapi/pull/14/commits/fbc838322d102b58aa7be783f855ea7ed0d527ec)

**Comment by DLZaan** [comment]
Hi, thank you for contributing, I merged the branch, but remember that Python 3.8 is near the end-of-life: https://devguide.python.org/versions/
